<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>TravailCommePapa</AssemblyName>
    <RootNamespace>TravailCommePapa</RootNamespace>
    <Product>Travail comme Papa</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="9.0.0" />
  </ItemGroup>

</Project>
